### ISSUE TITLE
多个 woker 进程的时候，延时任务 在阿里云的redis环境下会重复执行任务

### ISSUE THREAD

**Issue by usheweb** [top-think/think-queue#106]
自建的redis是不会出现重复执行任务的情况的，但是用 阿里云的redis 会出现重复执行任务的情况，怀疑是不是 事务无效导致的。
` /**
     * 移动延迟任务
     *
     * @param string $from
     * @param string $to
     * @param bool   $attempt
     */
    public function migrateExpiredJobs($from, $to, $attempt = true)
    {
        $this->redis->watch($from);

        $jobs = $this->getExpiredJobs(
            $from, $time = time()
        );
        if (count($jobs) > 0) {
            $this->transaction(function () use ($from, $to, $time, $jobs, $attempt) {
                $this->removeExpiredJobs($from, $time);
                $this->pushExpiredJobsOntoNewQueue($to, $jobs, $attempt);
            });
        }
        $this->redis->unwatch();
    }`

**Comment by kingfer30** [comment]
你这个是旧版的 v1.0的吧, 这个跟框架没有关系
另外阿里云的redis集群版有bug, 建议用主从:
https://www.jianshu.com/p/c1ff22ac693f

**Comment by senson2018** [comment]
可以尝试一下使用 setnx 做标记提前判断是否已执行了。

**Comment by qq475281441** [comment]
你的任务执行时间是不是超过了60s，超过60秒没结束的任务会被重试，需要设置配置文件的retry_after参数

**Comment by senson2018** [comment]
> retry_after

使用阿里云的话，需要在哪里设置呢？

**Comment by yunwuxin** [comment]
最新版的已经修正过了  redis集群keyslot的问题  https://redis.io/commands/cluster-keyslot
