### ISSUE TITLE
请问支持阿里云集群版不

### ISSUE THREAD

**Issue by YangHaHabiu** [top-think/think-queue#107]
测试单机正常出队列,使用阿里云集群版 不出队列,是有配置漏还是不支持集群版 tp5.1 think-queue/2.0.4

**Comment by kingfer30** [comment]
阿里云的集群版在处理事务上有bug，得用主从版，可参考：
https://www.jianshu.com/p/c1ff22ac693f

**Comment by YangHaHabiu** [comment]
> 阿里云的集群版在处理事务上有bug，得用主从版，可参考：
> https://www.jianshu.com/p/c1ff22ac693f

不需要更换主从版,有别的方法解决,在对于的key上加上{}包起来就解决了
