### ISSUE TITLE
thinkphp 5可以用吗？

### ISSUE THREAD

**Issue by male110** [top-think/think-queue#109]
Problem 1
    - topthink/think-queue v3.0.4 requires topthink/framework ^6.0.0 -> satisfiable by topthink/framework[6.0.x-dev, v6.0.0, v6.0.0-rc2, v6.0.0-rc3, v6.0.0-rc4, v6.0.0-rc5, v6.0.1, v6.0.2] but these conflict with your requirements or minimum-stability.
    - topthink/think-queue v3.0.3 requires topthink/framework ^6.0.0 -> satisfiable by topthink/framework[6.0.x-dev, v6.0.0, v6.0.0-rc2, v6.0.0-rc3, v6.0.0-rc4, v6.0.0-rc5, v6.0.1, v6.0.2] but these conflict with your requirements or minimum-stability.
    - topthink/think-queue v3.0.2 requires topthink/framework ^6.0.0 -> satisfiable by topthink/framework[6.0.x-dev, v6.0.0, v6.0.0-rc2, v6.0.0-rc3, v6.0.0-rc4, v6.0.0-rc5, v6.0.1, v6.0.2] but these conflict with your requirements or minimum-stability.
    - topthink/think-queue v3.0.1 requires topthink/framework ^6.0.0 -> satisfiable by topthink/framework[6.0.x-dev, v6.0.0, v6.0.0-rc2, v6.0.0-rc3, v6.0.0-rc4, v6.0.0-rc5, v6.0.1, v6.0.2] but these conflict with your requirements or minimum-stability.
    - topthink/think-queue v3.0.0 requires topthink/framework ^6.0.0 -> satisfiable by topthink/framework[6.0.x-dev, v6.0.0, v6.0.0-rc2, v6.0.0-rc3, v6.0.0-rc4, v6.0.0-rc5, v6.0.1, v6.0.2] but these conflict with your requirements or minimum-stability.
    - Installation request for topthink/think-queue ^3.0 -> satisfiable by topthink/think-queue[v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4].

 composer require topthink/think-queue
报错了

**Comment by kingfer30** [comment]
要升级到6以上
