### ISSUE TITLE
多个消费者消费job会出现重复消费

### ISSUE THREAD

**Issue by kingfer30** [top-think/think-queue#111]
版本：
"topthink/framework": "^6.0.2",
"topthink/think-queue": "^3.0",

描述：
我们有个异步导出的任务，由于导出量比较大，可能会超时或内存溢出，故执行脚本加了timeout和memory参数：
`php think queue:work --queue batch_download_task --sleep=3 --delay=15 --timeout=7200 --memory=1024`

在生产环境实际运行观察中，发现存在多个消费的情况：
![image](https://user-images.githubusercontent.com/34082198/80570642-c155ab80-8a2d-11ea-9c72-a82275aced37.png)

初步考虑是否是因为 timeout设置有问题？ 因为timeout默认是60秒，如果我设置了没生效，1分钟后另外一个进来消费？？

**Comment by kingfer30** [comment]
@yunwuxin @liu21st 帮忙看看这个问题

**Comment by kingfer30** [comment]
啥时候能回复呢...

**Comment by senson2018** [comment]
可以尝试使用 setnx 插入判断是否已执行过。

**Comment by kingfer30** [comment]
> 可以尝试使用 setnx 插入判断是否已执行过。

始终不是最佳解决方案..

**Comment by yunwuxin** [comment]
建议使用 php think queue:listen

**Comment by yunwuxin** [comment]
还有  你应该配置的是 retry_after 参数 不是timeout  或者把tries设置成1

**Comment by kingfer30** [comment]
listen也是一样
retry_after不支持这个参数的配置, 没有开放
tries可以设置成1，但是还是会有另外一个进程进来消费，只不过是因为tries为1，他消费不了，但是走了我们的异常逻辑
始终也不是最佳解决方案啊。。

**Comment by yunwuxin** [comment]
retry_after是在配置文件里配置  不是命令行上

**Comment by qq475281441** [comment]
今天我也遇到了这个问题，需要将配置文件的retry_after设置大一点，否则你一个队列执行时间超过60s就会被重试，如果你启动了多个进程就会出现重复消费的情况，我觉得retry_after参数最好跟命令的timeout参数使用同一个比较好，毕竟不是我每个任务都需要很长的时间去执行。
