### ISSUE TITLE
多应用模式下如何读取app下的config？

### ISSUE THREAD

**Issue by rongjch** [top-think/think-queue#112]
namespace app\jiu\job;
use think\queue\Job;

\think\facade\Config::get();
只能读取全局的config，不能读取jiu app里面的config，还有common.php也是同样情况。应该如何处理？

**Comment by kingfer30** [comment]
直接在env里面配置. 读取env

**Comment by TLingC** [comment]
```php
Config::load('jiu/conf', 'conf')
Config::get('conf');
```
