### ISSUE TITLE
在队列中使用app()方法不能引入类

### ISSUE THREAD

**Issue by Funny-dot** [top-think/think-queue#132]
在队列中使用app()方法不能引入类
    $r=$name ? app('wechat.mini_program.' . $name,  ["config"=>$config]) :
                    app('wechat.mini_program',  ["config"=>$config]);

报错
think\exception\ClassNotFoundException: class not exists: wechat.mini_program in C:\web\farm_backend\farm_backend\thinkphp\library\think\Container.php:442
Stack trace:
#0 C:\web\farm_backend\farm_backend\thinkphp\library\think\Container.php(284): think\Container->invokeClass('wechat.mini_pro...', Array)
#1 C:\web\farm_backend\farm_backend\thinkphp\library\think\Container.php(132): think\Container->make('wechat.mini_pro...', Array, false)
#2 C:\web\farm_backend\farm_backend\thinkphp\helper.php(77): think\Container::get('wechat.mini_pro...', Array, false)
#3 C:\web\farm_backend\farm_backend\vendor\naixiaoxin\think-wechat\src\Facade.php(58): app('wechat.mini_pro...', Array)
#4 C:\web\farm_backend\farm_backend\application\server\WxHelper.php(580): Naixiaoxin\ThinkWechat\Facade::miniProgram('', Array)
#5 C:\web\farm_backend\farm_backend\application\common\job\WechatMsgQueue.php(15): app\server\WxHelper::miniProgram('1')

**Comment by yunwuxin** [comment]
你这个错误信息 不是很明显是你$name传入了空值么
