### ISSUE TITLE
安装后提示think\Manager类找不到

### ISSUE THREAD

**Issue by jianchang512** [top-think/think-queue#135]
composer require topthink/think-queue
安装的最后，提示这个错误

PHP Fatal error:  Class 'think\Manager' not found in /www/wwwroot/xnb.wosuu.com/vendor/topthink/think-queue/src/Queue.php on line 25

打开这个文件看了下，
class Queue extends Manager

类是这样定义的，Manager父类在哪里，没这个文件

**Comment by yunwuxin** [comment]
检查tp和think-queue版本
