### ISSUE TITLE
$job->release($delay)里的delay是不是没有实装？

### ISSUE THREAD

**Issue by michaelgx2** [top-think/think-queue#136]
源代码：
/**
     * Release the job back into the queue.
     * @param  int $delay
     * @return void
     */
    public function release($delay = 0)
    {
        $this->released = true;
    }

我试图用队列来执行一个并不需要计时精确的定时任务，结果一瞬间给我执行了几百次，然后我翻了下源代码发现参数中的$delay完全没用到啊？

**Comment by OverNaive** [comment]
`think\queue\Job` 只是个抽象类，如果你用的是 redis 驱动，那么你找的应该是 `think\queue\job\Redis`，他是继承 `think\queue\Job`。

那么找到的 `release` 方法如下：

```
    /**
     * 重新发布任务
     *
     * @param int $delay
     * @return void
     */
    public function release($delay = 0)
    {
        parent::release($delay);

        $this->redis->deleteAndRelease($this->queue, $this, $delay);
    }
```

**Comment by michaelgx2** [comment]
> `think\queue\Job` 只是个抽象类，如果你用的是 redis 驱动，那么你找的应该是 `think\queue\job\Redis`，他是继承 `think\queue\Job`。
> 
> 那么找到的 `release` 方法如下：
> 
> ```
>     /**
>      * 重新发布任务
>      *
>      * @param int $delay
>      * @return void
>      */
>     public function release($delay = 0)
>     {
>         parent::release($delay);
> 
>         $this->redis->deleteAndRelease($this->queue, $this, $delay);
>     }
> ```

是我穿进去的delay参数有问题，我的
