### ISSUE TITLE
请求支持一下symfony/process新版本

### ISSUE THREAD

**Issue by cuixiaogang110** [top-think/think-queue#137]
能否支持一下新版本，谢谢各位大佬了
![image](https://user-images.githubusercontent.com/27757656/109590237-956fee80-7b46-11eb-9985-cdef5d06eabc.png)

**Comment by ninetian** [comment]
我也遇到这破事了.......

**Comment by HikingTsang** [comment]
我这边也是，composer安装了PHP-FFMpeg，再安装think-queque，然后提示安装symfony/process版本太高

**Comment by dxing1202** [comment]
我也碰到这个问题，有什么好解决方法吗

**Comment by tsbanmeng** [comment]
我也遇到了，think-queue引用的symfony/process版本太低了。。和PHP-FFMpeg库冲突。

**Comment by coffin-laughter** [comment]
symfony/process 的版本真的有点太低了，强烈建议适当的升级一下，不然好多要用的包依赖都报版本太低冲突了

**Comment by Pink0410** [comment]
> 
怎么解决的啊

**Comment by yangpans** [comment]
有解决方案吗

**Comment by yuanzhihai** [comment]
> > 
> 
> 怎么解决的啊

自己维护一版吧 没人理你

**Comment by yunwuxin** [comment]
支持了
