### ISSUE TITLE
supervisor+redis开启多进程来执行队列的时候会被执行两次

### ISSUE THREAD

**Issue by CauliFlowor** [top-think/think-queue#138]
![image](https://user-images.githubusercontent.com/40047557/110881411-4a5e9400-831b-11eb-8d82-2ef5e321ea73.png)
图片显示这个任务执行了两次

supervisor配置文件是这样写的
![image](https://user-images.githubusercontent.com/40047557/110881476-62ceae80-831b-11eb-9a37-5e7ea9a5e799.png)

请问知道是什么原因吗

**Comment by yunwuxin** [comment]
没看到上面那条没有Processed的日志么
说明上面那条执行失败了(比如超时了被kill掉了)  下面的是重试

**Comment by CauliFlowor** [comment]
> 没看到上面那条没有Processed的日志么
> 说明上面那条执行失败了(比如超时了被kill掉了) 下面的是重试

--timeout=3600 才过了一分钟

**Comment by yunwuxin** [comment]
https://github.com/top-think/think-queue/blob/3.0/src/queue/connector/Redis.php#L76

有个retry_after 参数   60秒之后就会重试

**Comment by CauliFlowor** [comment]
> https://github.com/top-think/think-queue/blob/3.0/src/queue/connector/Redis.php#L76
> 
> 有个retry_after 参数 60秒之后就会重试

ok明白了，谢谢
