### ISSUE TITLE
think-queue 队列运行一段时间后, 队列再进数据, 就不消费了, 重启才能生效

### ISSUE THREAD

**Issue by lidemo000** [top-think/think-queue#144]
public function fire(Job $job,$data)
    {
        // 有些消息在到达消费者时,可能已经不再需要执行了
        $isJobStillNeedToBeDone = $this->checkDatabaseToSeeIfJobNeedToBeDone($data);
        if(!$isJobStillNeedToBeDone){
            $job->delete();
            return true;
        }

        $isJobDone = $this->doPushJob($data);

        if ($isJobDone) {
            // 如果任务执行成功， 记得删除任务
            $job->delete();

        }else{

            //通过这个方法可以检查这个任务已经重试了几次了
//             print("<warn>Hello Job has been retried more than 3 times!"."</warn>\n");

            $job->delete();

        }
    }

**Comment by yunwuxin** [comment]
已经修正了  这个是redis驱动不支持断线重连引起的
