### ISSUE TITLE
能不能支持将未执行的但已在延迟队列里的消息进行回收（删除）？

### ISSUE THREAD

**Issue by nbczw8750** [top-think/think-queue#149]
如题
能不能支持删除尚未执行的消息？
业务上需要，例如会议通知，原定在30分钟后通知，但是会议突然取消或者改时间了，但是消息已经进入了延迟队列，需要把他删掉。

**Comment by yunwuxin** [comment]
换个思路？
队列消费的时候进行检查

**Comment by nbczw8750** [comment]
换思路实现也行，支持要多去查询一遍。 原则上消息撤回在消息队列里，是需要实现的功能。

**Comment by yunwuxin** [comment]
队列一般不会考虑取消任务，都是在消费端做处理
