### ISSUE TITLE
队列消费者找不到执行路径

### ISSUE THREAD

**Issue by suliang** [top-think/think-queue#156]
当使用TP框架（6.0.3）时候，多应用模式，应用的目录文件名为驼峰式（有大写字母）时，
think-queue/src/queue/Job.php 文件的179行， 
【$name = ($this->app->config->get('app.app_namespace') ?: 'app\\') . ($app ? strtolower($app) . '\\' : '') . 'job\\' . $name;】
会把目录强制转为小写，
导致找不到消费者的执行路径（报类不存在）。
这里没有必要强制转换小写吧。

**Comment by sonhineboy** [comment]
可以把详细的代码，和报错信息发出来，你这样说都没人能知道具体是什么原因

**Comment by suliang** [comment]
> 可以把详细的代码，和报错信息发出来，你这样说都没人能知道具体是什么原因

假设多应用模式，某个应用名（目录名）为  aaBb,
应用（aaBb）的job目录下存在Notice 类,
生产者： Queue::push('aaBb/Notice', $key, 'topic名称');
命令行执行 php think queue:listen --queue topic名称
队列消费的时候，
报错信息： class not exists: app\aabb\job\Notice

原因是  应用名被强制转换为了全小写。

**Comment by sonhineboy** [comment]
Queue::push('aaBb/Notice', $key, 'topic名称');
这里的'aaBb/Notice',直接改成Notice::class,试试

**Comment by yunwuxin** [comment]
使用完整类名
