### ISSUE TITLE
PHP Fatal error:  Uncaught think\exception\ErrorException: Swoole\Event::rshutdown(): Event::wait() in shutdown function is deprecated in Unknown:0

### ISSUE THREAD

**Issue by ZhangTianyi-1998** [top-think/think-queue#157]
任务执行完成后就会报这个错误

think-framework  6.0.8
think-queue 3.0.6
think-swoole 4.0.5
swoole    4.8.0

# php think queue:listen --memory 1280 --timeout 3600
[2021-11-15 12:06:39][sfXEbCQCyyIBDtVHurpheEebSXfsttAV] Processing: DownloadDataReport@download
"done"
array:2 [
  "code" => 0
  "data" => "/mnt/c/Users/zhang/PhpstormProjects/national_health/runtime/storage/word/数据报告20211115115248.docx"
]
[2021-11-15 12:08:52][sfXEbCQCyyIBDtVHurpheEebSXfsttAV] Processed:  DownloadDataReport@download
PHP Fatal error:  Uncaught think\exception\ErrorException: Swoole\Event::rshutdown(): Event::wait() in shutdown function is deprecated in Unknown:0
Stack trace:
#0 [internal function]: think\initializer\Error->appError()
#1 [internal function]: Swoole\Event::rshutdown()
#2 {main}
  thrown in Unknown on line 0

代码
`try {

            if ($job->attempts() > 5) {
                $job->delete();
            }

            (new TaskModel())->updateTask($data['taskId'], 1, 0, '', $data['userInfo']);
            $res = (new DataReportDownloadModel())->downloadDataReportExpand($data['requestGet'], $data['managerOrganizationId'], $data['taskId']);
            cliDump($res);
            if ($res['code'] == 0) {
                $r = (new TaskModel())->updateTask($data['taskId'], 2, 100, $res['data'], $data['userInfo']);
            } else {
                $r = (new TaskModel())->updateTask($data['taskId'], 3, 0, '', $data['userInfo']);
            }

            $job->delete();
        } catch (Exception $exception) {
            $job->release(3);
        }`

**Comment by yunwuxin** [comment]
这是swoole的错误
