### ISSUE TITLE
使用队列报错 类不存在: swoole.server不存在,macOs Monterry

### ISSUE THREAD

**Issue by HalYang01** [top-think/think-queue#160]
{
    "code":0,
    "message":"类不存在: swoole.server",
    "traces":[
        {
            "name":"think\\exception\\ClassNotFoundException",
            "file":"\/Users\/xuwenjie\/wwwroot\/pffsever\/vendor\/topthink\/framework\/src\/think\/Container.php",
            "line":377,
            "code":0,
            "message":"类不存在: swoole.server",
            "trace":[
                {
                    "file":"/Container.php",
                    "line":251,
                    "function":"invokeClass",
                    "class":"think\\Container",
                    "type":"->",
                    "args":[
                        "swoole.server",
                        [

                        ]
                    ]
               }

**Comment by yunwuxin** [comment]
与本扩展无关
