### ISSUE TITLE
任务执行失败，修复后，重新执行任务成功，但是无法删除任务

### ISSUE THREAD

**Issue by fuzuAdmin** [top-think/think-queue#167]
```
namespace app\web\job;

use think\queue\Job;
use think\facade\Event;

class Register{
    
    /**
     * 增加用户邀请人数量
     */
    public function userInvites(Job $job, $data){

        echo '任务次数：'.$job->attempts()."\r\n";

        if ($job->attempts() > 1) {
            $job->delete();
            // 重新发布这个任务
            $job->release(5); //$delay为延迟时间
        }

            //增加邀请用户邀请数量
            $res = Event::trigger('UserInvites', ['user_id'=>$data['user_id']]);

            if($res){

                echo "完成了~\r\n";
                var_dump($job->isDeleted());

                //如果任务执行成功后 记得删除任务，不然这个任务会重复执行，直到达到最大重试次数后失败后，执行failed方法
                $job->delete();

            }
    }
    
    public function failed($data){
    
        // ...任务达到最大重试次数后，失败了
    
        echo '搞不定了'."\r\n";
    
    }

}
```

//增加邀请用户邀请数量
$res = Event::trigger('UserInvites', ['user_id'=>$data['user_id']]);

这块业务逻辑异常导致任务失败，修复之后，再重启服务提示任务成功了，并且调用$job->delete()删除任务，输出$job->isDeleted()显示为true，但是还是会继续执行这个任务，这是为什么呢

**Comment by note-sun** [comment]
> ```
> namespace app\web\job;
> 
> use think\queue\Job;
> use think\facade\Event;
> 
> class Register{
>     
>     /**
>      * 增加用户邀请人数量
>      */
>     public function userInvites(Job $job, $data){
> 
>         echo '任务次数：'.$job->attempts()."\r\n";
> 
>         if ($job->attempts() > 1) {
>             $job->delete();
>             // 重新发布这个任务
>             $job->release(5); //$delay为延迟时间
>         }
> 
>             //增加邀请用户邀请数量
>             $res = Event::trigger('UserInvites', ['user_id'=>$data['user_id']]);
> 
>             if($res){
> 
>                 echo "完成了~\r\n";
>                 var_dump($job->isDeleted());
> 
>                 //如果任务执行成功后 记得删除任务，不然这个任务会重复执行，直到达到最大重试次数后失败后，执行failed方法
>                 $job->delete();
> 
>             }
>     }
>     
>     public function failed($data){
>     
>         // ...任务达到最大重试次数后，失败了
>     
>         echo '搞不定了'."\r\n";
>     
>     }
> 
> }
> ```
> 
> //增加邀请用户邀请数量 $res = Event::trigger('UserInvites', ['user_id'=>$data['user_id']]);
> 
> 这块业务逻辑异常导致任务失败，修复之后，再重启服务提示任务成功了，并且调用$job->delete()删除任务，输出$job->isDeleted()显示为true，但是还是会继续执行这个任务，这是为什么呢

为什么呢？
