### ISSUE TITLE
expire 的配置疑惑

### ISSUE THREAD

**Issue by coolseven** [top-think/think-queue#17]
@yunwuxin 你好，在使用tp-queue 这个队列库时，对于 expire 项的配置，有一处比较疑惑的地方：
假设现在存在两个队列，分别为 QueueA ， QueueB ，
预估 QueueA ， QueueB 中的每个job的大约耗时分别为 40秒 ， 400秒。
那我们的expire 应该配置为 60 还是 600 呢？
如果配置为 60 的话，那么如果使用多个消费进程去处理 QueueB ， 那么 QueueB 中的任务是不是频繁地被误作超时处理？
如果配置为 600 的话，那 QueueA 中真正超时的任务是不是总是得不到及时的恢复？

我用的是 php think queue:work --daemon 模式。

**Comment by yunwuxin** [comment]
#11 
下个版本打算支持类似这个多组配置 
配置如下
```
return [
    'default' => 'redis1',
     
     'redis1' => [
         'driver'='redis'
         'expire'     => 40,
         'default'    => 'default',
         'host'       => '127.0.0.1',
         'port'       => 6379
    ],
     'redis1' => [
         'driver'='redis'
         'expire'     => 400,
         'default'    => 'default',
         'host'       => '127.0.0.1',
         'port'       => 6379
    ],
 ];
```
监听的时候选择connector
```
php think queue:work --daemon --connector=redis1
```
推送任务的时候也同样可以指定

**Comment by coolseven** [comment]
@yunwuxin 好的，谢谢，期待早日推出！  对应的PR我就关闭了。
