### ISSUE TITLE
php think queue:listen 

### ISSUE THREAD

**Issue by kevin19a** [top-think/think-queue#171]
执行queue
带 queue参数就可以执行
不带，想监听全部就不行。
 type类型是redis

**Comment by Jayin** [comment]
没有监听全部一说，默认的queue名称就是default

**Comment by cffycls** [comment]
不对queue命名、保持默认的linten 空；命名，linsten --queue 新名字会出现不处理的问题，看到jobs表里的名字去listen也经常会出现不动-不执行的情况。感觉是执行了一下，然后就没有然后了

**Comment by yunwuxin** [comment]
默认队列名是default   推入的队列要和通过listen消费的队列名一致  不存在没有命名的

**Comment by cffycls** [comment]
default是默认队列名

**Comment by cffycls** [comment]
找到问题了，是执行中断、卡住，然后全部队列不开始执行
