### ISSUE TITLE
supervisor使用 queue:listen 设置timeout不起作用

### ISSUE THREAD

**Issue by lushaobo** [top-think/think-queue#178]
命令：
`/usr/local/php/bin/php /www/wwwroot/app_pro/think queue:listen --queue=cs_queue_test --tries=3 --timeout=65`

使用supervisor启动的话，则执行到60秒的时候，则会自动进行重试

![图片](https://user-images.githubusercontent.com/5574978/219948838-fe04a206-9649-4488-9188-29fbab3aea0c.png)

然后就会出现同时有3条进程在执行同一段代码

----------------
打开命令行工具，直接复制上面代码进行执行，则为正常。

**Comment by yunwuxin** [comment]
--tries=3  不是你自己设置的 尝试3次么

**Comment by lushaobo** [comment]
不是重试的问题，是 我设置了  timeout = 65， 但脚本执行到 60 就会出现重试。TestJob 代码如下：

**Comment by lushaobo** [comment]
sleep(63);
var_dump($data);

**Comment by lushaobo** [comment]
topthink/framework 版本为 6.1.2
topthink/think-queue 版本为3.0.7
现在主要问题是，  queue:listen  --timeout 参数在 supervisor 里面好像不起作用（任务只要超出60秒就会自动重启一个，但旧的进程还在执行）。 我直接复制命令在 终端 执行，则能正常的执行。

**Comment by lushaobo** [comment]
![图片](https://user-images.githubusercontent.com/5574978/219949458-948a2127-6daf-4817-ac68-df3b2c942343.png)
这个是 supervisrod 的配置

**Comment by yunwuxin** [comment]
参考 #138

**Comment by lushaobo** [comment]
好的，多谢，请问这个参数能修改吗？

**Comment by lushaobo** [comment]
好的，多谢，不过这种设计好容易误导人。
