### ISSUE TITLE
安装时报错： Call to undefined method think\Console::addDefaultCommands()

### ISSUE THREAD

**Issue by waynesun01** [top-think/think-queue#179]
@php think service:discover

Fatal error: Uncaught Error: Call to undefined method think\Console::addDefaultCommands() in D:\phpstudy_pro\WWW\virtually\server\vendor\topthink\think-queue\src\common.php:12       
Stack trace:
#0 D:\phpstudy_pro\WWW\virtually\server\vendor\composer\autoload_real.php(41): require()
#1 D:\phpstudy_pro\WWW\virtually\server\vendor\composer\autoload_real.php(45): {closure}()
#2 D:\phpstudy_pro\WWW\virtually\server\vendor\autoload.php(25): ComposerAutoloaderInitd2a74ba94e266cc4f45a64c54a292d7e::getLoader()
#3 D:\phpstudy_pro\WWW\virtually\server\think(7): require('...')
#4 {main}
  thrown in D:\phpstudy_pro\WWW\virtually\server\vendor\topthink\think-queue\src\common.php on line 12
Script @php think service:discover handling the post-autoload-dump event returned with error code 255

**Comment by waynesun01** [comment]
thinkphp6
php8.0.2
think-queue 2.0.3

**Comment by rabbit-dog** [comment]
![62260200370e8874963c1aff381d0b3](https://github.com/top-think/think-queue/assets/30332327/2f51ca59-c782-4277-b3a2-be450cee9688)

**Comment by 1nFrastr** [comment]
删掉composer.lock文件，重新安装依赖

**Comment by xiaoxuyp** [comment]
> 删掉composer.lock文件，重新安装依赖

有用

**Comment by AilonHuang** [comment]
> 删掉composer.lock文件，重新安装依赖

有用
