### ISSUE TITLE
如果不指定queue就不执行队列中的任务？

### ISSUE THREAD

**Issue by nicetake** [top-think/think-queue#18]
如果使用 php think queue:listen 则不会执行队列中的任务。
如果使用 php think queue:work --queue add_user 则可以执行

**Comment by yunwuxin** [comment]
php think queue:listen  等同于   php think queue:listen --queue default

按照你的需求 要这么写 php think queue:listen --queue add_user

**Comment by nicetake** [comment]
谢谢，劳驾在请教下，如果多模块就必须开启多个cli模式，
不能
php think queue:work --dameon --queue add_user del_user update_user
同一个进程处理多个任务

**Comment by nicetake** [comment]
明白了，根据不同的参数调用不同的任务，谢谢啦
