### ISSUE TITLE
消费队列时，读取不到env的配置

### ISSUE THREAD

**Issue by xuhang-1211** [top-think/think-queue#184]
thinkphp6 queue、database这些配置文件里的配置项都是读取env的配置，但是消费队列时，这些配置都读取不到
![image](https://github.com/top-think/think-queue/assets/15684376/88aa6b35-3f03-4867-8bb6-ec24edd8fbc9)

**Comment by watsonhaw5566** [comment]
@xuhang-1211  可以正常使用了吗，我也遇到了这个问题
