### ISSUE TITLE
Call to undefined method think\helper\Str::studly()

### ISSUE THREAD

**Issue by xiucaiwu** [top-think/think-queue#23]
在vendor/topthink/think-queue/src/Queue.php第33行
`$options = Config::get('queue');`
$options为null,其实他应该获取的是application/extra/queue.php中的配置
在vendor/topthink/think-queue/src/Queue.php第38行
`$class = false !== strpos($type, '\\') ? $type : '\\think\\queue\\connector\\' . Str::studly($type);`
studly这个方法不存在
下面是我修改后的方法
在application/config.php添加
`    'queue'     => [
        'type'      => 'redis',
        'expire'     => 60,
        'default'    => 'default',
        'host'       => '127.0.0.1',
        'port'       => 6379,
        'password'   => '',
        'select'     => 0,
        'timeout'    => 0,
        'persistent' => false
    ],`
把`$class = false !== strpos($type, '\\') ? $type : '\\think\\queue\\connector\\' . Str::studly($type);`改为`$class = false !== strpos($type, '\\') ? $type : '\\think\\queue\\connector\\' . ucfirst($type);`
运行正常!

**Comment by yunwuxin** [comment]
你依赖没安装好吧 
Str::studly
是think-helper 这个包里的
