### ISSUE TITLE
入口文件index.php定义config目录执行队列失效

### ISSUE THREAD

**Issue by phpcodegroup** [top-think/think-queue#24]
入口文件index.php
define('CONF_PATH', \_\_DIR\_\_  . '/../config/'); 
后，在application/config 目录定义 
E:\WEBROOT\TP5-BASE\CONFIG
│  config.php
│  database.php
│  route.php
│  tags.php
│
└─extra
        queue.php
这时执行队列 php think queue:listen 就失败

不在index.php文件定义 config目录，移动相关目录到application就可以

不知道哪里出的问题

**Comment by phpcodegroup** [comment]
哈哈，解决了
application 下 也复制一份config 目录下的文件和目录就可以了，但是这样是不是不定义CONF_PATH 就没有意义了呢？

**Comment by coolseven** [comment]
@phpcodegroup 你需要在 命令行的入口文件 `think` 中也定义一下新的config目录：
define('CONF_PATH', __DIR__ . '/config/');
