### ISSUE TITLE
项目根目录外执行队列报错：Could not open input file: think

### ISSUE THREAD

**Issue by Zjmainstay** [top-think/think-queue#33]
使用时候发现，如果不在项目根目录下运行会出现报错：Could not open input file: think，经排查发现，think-queue/src/queue/Listener.php Line 52 直接使用了 think作为命令名，导致think文件定位失败。

原代码：
```
        $this->workerCommand =
            '"' . PHP_BINARY . '" think queue:work --queue="%s" --delay=%s --memory=%s --sleep=%s --tries=%s';
```

建议修改为：
```
$this->workerCommand =
            '"' . PHP_BINARY . '" ' . ROOT_PATH . 'think queue:work --queue="%s" --delay=%s --memory=%s --sleep=%s --tries=%s';
```

**Comment by coolseven** [comment]
@Zjmainstay 按照你的排查思路,提交了一个PR https://github.com/top-think/think-queue/pull/34.   
解决方式和你的解决方式有一点区别: 
你的解决方式中, think 脚本通过绝对路径来定位, 无需借助 current working directory.
PR中,通过设置 worker 进程的 cwd, 从而允许通过相对路径来定位 think 脚本
仅供参考.

**Comment by Zjmainstay** [comment]
Good
