### ISSUE TITLE
TP5.1 下composer安装  Database模式报错

### ISSUE THREAD

**Issue by HFLdragon** [top-think/think-queue#37]
[5.1文档：原来的应用extra目录下面的配置文件直接移动到config目录下面](https://www.kancloud.cn/manual/thinkphp5_1/354155)
 也就是说2.1.0的配置文件(位于 `application/extra/queue.php`) 
 使用 $options = \think\facade\Config::pull('queue'); 是获取不到的
 要移动到 config 目录下，然后除了除Sync模式，其他均会报此错，怀疑还是connector构造函数array_merge处报错

 [think\exception\ErrorException]   
 array_merge(): Argument #1 is not an array

**Comment by liu21st** [comment]
配置文件肯定是按照5.1的规范位置来放置的，你的配置文件内容是什么？

**Comment by HFLdragon** [comment]
composer安装think-queue，然后将application/extra/queue.php 移动到 config/queue.php，配置如下：
`'connector' => 'Database'        
'expire'  => 60,
'default' => 'default',
'table'   => 'tp_jobs',
'dsn'     => 'mysql://root:root@127.0.0.1:3306/test#utf8'`

测试Redis没问题

**Comment by liu21st** [comment]
已经修正
