### ISSUE TITLE
异步执行无效

### ISSUE THREAD

**Issue by vemce** [top-think/think-queue#38]
将connector设为sync时能正常执行，改为database或redis后，调用Queue::push能把数据插入到mysql或redis中，但是执行php think queue:listen或php think queue:work --daemon后台任务并不能被执行

**Comment by HFLdragon** [comment]
这是tp5.1下的bug，已修复，见[#37](https://github.com/top-think/think-queue/issues/37)，Redis是可以的

**Comment by leruge** [comment]
我只是加入队列push后，不管是sync还是redis，任务就马上执行了，并没有运行php think queue:listen，就算运行了php think queue:listen后fire中的print也没有在控制台，这是为什么？
