### ISSUE TITLE
Queue类找不到

### ISSUE THREAD

**Issue by phpyii** [top-think/think-queue#4]
把Queue类移到外边找不到了。。。怎么还发布了个稳定版
```
PHP Fatal error:  Class 'think\queue\Queue' not found in E:\test\tp5\vendor\topt
hink\think-queue\src\queue\Worker.php on line 54
```

**Comment by yunwuxin** [comment]
已经升了版本号了  原来是1.0.*   现在是1.1了 原来的不会更新到这个版本的  除非你自己指定到这个版本了

**Comment by phpyii** [comment]
好吧

**Comment by zoujingli** [comment]
我的也更新到了这个版本，没有进行版本指定呢。
```
Exception trace:
 () at /home/wwwroot/service/vendor/topthink/think-queue/src/queue/Worker.php:54
 think\Error::appShutdown() at n/a:n/a
```
在worker.php 加上 `use think\Queue;`

**Comment by yunwuxin** [comment]
@zoujingli 已修正

**Comment by phpyii** [comment]
@zoujingli  我现在监听不到任务了，你能监听到吗？

**Comment by zoujingli** [comment]
在worker.php 加上 `use think\Queue; ` 可以正常使用，用` listen` 调试下

**Comment by zoujingli** [comment]
@yunwuxin @phpyii 已使用v1.1.1，一切正常 by 助手函数

**Comment by phpyii** [comment]
@zoujingli   我用了listen 监听不到 不知道什么原因

**Comment by zoujingli** [comment]
@yunwuxin 可以给一个 queue:stop 指令么

**Comment by phpyii** [comment]
@zoujingli 而且我的任务 打印日志 发布后直接就执行了 延迟也不起作用

**Comment by yunwuxin** [comment]
@phpyii 你用的什么驱动Sync？配置文件改了  在extra下面

**Comment by phpyii** [comment]
@yunwuxin  是的安装最新的think-queue默认产生了extra下的queue配置文件 默认是Sync

**Comment by yunwuxin** [comment]
@phpyii 这个是同步驱动  不添加到队列的  直接执行的   开发的时候测试用的

**Comment by zoujingli** [comment]
是这样子吧 @yunwuxin 
```
return [
    'connector' => 'database',
    'table'     => 'system_jobs',
];
```

**Comment by zoujingli** [comment]
@yunwuxin 在发起任务时，可以指定配置么

**Comment by yunwuxin** [comment]
@zoujingli  queue:restart这个命令其实就是queue:stop 只是如果配合Supervisor使用的话 会自动重启

**Comment by yunwuxin** [comment]
@zoujingli 目前不可以  后续版本会增加

**Comment by zoujingli** [comment]
@yunwuxin 我的配置如上，发布的任务没有写到数据库

**Comment by zoujingli** [comment]
@yunwuxin 如果可以，把stop放出来吧 ，嘿嘿

**Comment by phpyii** [comment]
@yunwuxin @zoujingli  以前的版本也是用Sync驱动 但是listen可以监听到

**Comment by yunwuxin** [comment]
@zoujingli  是不是被执行掉了 执行了后 数据库里的任务会被删掉的  

queue:restart就是stop 你要stop  执行queue:restart就可以了

**Comment by zoujingli** [comment]
@yunwuxin 我的任务时间比较久，不会一闪而过的

**Comment by yunwuxin** [comment]
@phpyii 不可能  你去看看代码就知道了 sync驱动是直接执行的 不会被添加到队列里去的

**Comment by zoujingli** [comment]
@yunwuxin `queue('app\\wechat\\Jobs@fans', ['appid' => $this->real_appid, 'index' => $index]);`这样会写库么，已经配置数据库

**Comment by zoujingli** [comment]
在项目中，我希望可以获得任务执行状态，应该从哪里去找。
比如，同一个业务，已经创建了任务，那么就需要待完成才能创建下一个。
比如，任务处理中，设置执行进度，调用者可以使用什么key来获取到进度，大数据处理时很需要

**Comment by yunwuxin** [comment]
@zoujingli 已修正

**Comment by yunwuxin** [comment]
@zoujingli 任务进度的问题  这个是由你业务自己控制的  
比如你在处理任务的时候  分段写一下数据库 当前进行到哪了就是了

**Comment by zoujingli** [comment]
@yunwuxin 目前好像不支持获取到指定的任务对象，只能在 data中加入一个key值，通过like来查找。不知可以加一个query机制么，创建时指定query的key，其它地方只能合适key就能找到任务对象。至于进度的话，看把他放到 $job 上，通过set去更新进度，其它地方通过query获取任务对象，自然进度也有了

**Comment by yunwuxin** [comment]
@zoujingli 你没明白我的意思  这个任务对象你要获取了干嘛，各个驱动的存储方式都不一样  
任务进度应该保存在业务表里  不同的业务  进度展示也是不同的  举个最简单的例子 ：上传视频处理  

上传视频后 你的视频表里插入了一条数据 状态设为待处理   然后在你定义的Job那个类里开始处理的时候  你把这条数据的状态设为处理中   处理完成后把这条数据状态设为已处理  中间还可以穿插任意个状态  

你要显示状态给用户看  直接到这个视频表里读取状态就是了

**Comment by phpyii** [comment]
我更新到了1.1.2   
我也建了个jobs表 用数据库Database引擎  任务增加到数据库了  还是监听不到   
队列日志是这个 SELECT * FROM `tp5_jobs` WHERE  `queue` = 'default'  AND `reserved` = 0  AND `available_at` <= 1480567246 ORDER BY `id`  asc LIMIT 1   
难道不是查询所有的任务吗  只查询default吗

**Comment by yunwuxin** [comment]
default是队列名   你启动listen命令的时候 可以指定的  

这样可以启动多个listen进程  同步处理不同队列的任务

**Comment by phpyii** [comment]
@yunwuxin  监听到了 必须指定队列名。。。
