### ISSUE TITLE
1.1.4怎么不能异步执行

### ISSUE THREAD

**Issue by 617450941** [top-think/think-queue#45]
1.1.4怎么不能异步执行 在执行逻辑里加了sleep验证是否异步   结果还是同步

**Comment by 617450941** [comment]
如果有的任务是耗时的 很容易阻塞后面的任务 这样效率感觉好低啊

**Comment by hainuo** [comment]
队列的意思本身就是 一个执行完了再进行另一个，你需要并行的话 建议使用多个队列

**Comment by 617450941** [comment]
命令我看了下 好像一条命令只能执行一个队列 要多个队列执行 就要执行多条命令  有没办法一条命令执行多个队列

**Comment by hainuo** [comment]
你再创建的时候定义到同一个队列中就好了  或者你提交一个pr

**Comment by 617450941** [comment]
$job_handler_class_name = 'app\job\Sms'; 
            $job_queue_name = "kfQueue"; 
            $job_data = ['send_phone' => $phone, 'company_id' => $company_id, 'content' => "您的短信验证码为{$verify_code}" ] ;
            Queue::push($job_handler_class_name , $job_data , $job_queue_name);	

提交到同一个队列任务是串行执行的

**Comment by yunwuxin** [comment]
一条命令就是一个队列   要多个队列的话 就使用多条命令  

推荐使用supervisor来管理
