### ISSUE TITLE
listen模式下CPU资源占用过高的问题

### ISSUE THREAD

**Issue by Zhwt** [top-think/think-queue#46]
在listen模式下, 什么都没开始执行, 用于listen的php-cli会稳定吃掉一个核心的资源
![image](https://user-images.githubusercontent.com/4744830/38414011-e44eb8d6-39bf-11e8-8a87-3509ae1f45f8.png)
队列的代码见 [coolseven的教程](https://github.com/coolseven/notes/tree/master/thinkphp-queue), 用了一个简单的HelloWorld例子进行测试, 因为还并没有开始执行任务, 应该是listen的循环部分有问题
think-queue版本为1.1.4, 没有修改过框架
![image](https://user-images.githubusercontent.com/4744830/38414441-106460fa-39c1-11e8-8e8c-c2db267ed31b.png)
系统环境:
Windows 10 x64 1511
php 7.0.1 nts

**Comment by Zhwt** [comment]
@yikuo123 目前我的解决方法是[在框架里面加了一个sleep函数](https://github.com/top-think/think-queue/pull/47), 解决的不完美, 两次执行队列间会间隔3s, 但是解决了在测试环境下导致大量CPU时间处于等io的问题

**Comment by hainuo** [comment]
这个只能提升硬件性能，在2核4g的ecs上 两个queue命令可以吃掉70%的cpu，所以只能提升cpu数量或者提升cpu的性能

**Comment by yunwuxin** [comment]
生产模式下推荐使用 php think queue:work --daemon  

php think queue:listen 主要是测试的时候使用

**Comment by hainuo** [comment]
@yunwuxin 原来如此，我也一直奇怪为啥我自己写了一个脚本自动拉取 git 占用的 cpu 没这么高呢

**Comment by peter-biu** [comment]
> 生产模式下推荐使用 php think queue:work --daemon
> 
> php think queue:listen 主要是测试的时候使用

3.0 版本php think queue:work  没有这个--daemon参 ，还有什么办法解决 php think queue:listen 拉高cpu的情况嘛  @yunwuxin
