### ISSUE TITLE
使用数据库记录列队时，连接数累积越来越多

### ISSUE THREAD

**Issue by zoujingli** [top-think/think-queue#5]
使用数据库记录列队时，连接数累积越来越多

**Comment by zoujingli** [comment]
就算不创建任务，数据库连接数也会累加

**Comment by yunwuxin** [comment]
用的listen还是work --daemon

**Comment by zoujingli** [comment]
work --daemon &

**Comment by zoujingli** [comment]
```
init─┬─AliHids───4*[{AliHids}]
     ├─AliYunDun───12*[{AliYunDun}]
     ├─AliYunDunUpdate───3*[{AliYunDunUpdat}]
     ├─aegis_quartz───4*[{aegis_quartz}]
     ├─crond
     ├─gshelld───3*[{gshelld}]
     ├─6*[mingetty]
     ├─mongod───10*[{mongod}]
     ├─mysqld_safe───mysqld───928*[{mysqld}]
     ├─nginx───2*[nginx]
     ├─nscd───18*[{nscd}]
     ├─ntpd
     ├─2*[php]
     ├─php-fpm───5*[php-fpm]
     ├─php-fpm───11*[php-fpm]
     ├─pure-ftpd
     ├─rsyslogd───3*[{rsyslogd}]
     ├─sshd─┬─6*[sshd───bash]
     │      └─sshd───bash───pstree
     └─udevd───2*[udevd]
```
只要一启动 queue，mysql 连接数据就慢慢的暴涨

**Comment by zoujingli** [comment]
启动命令
```
nohup php think queue:work --daemon  &
```

**Comment by yunwuxin** [comment]
未执行的时候 
![image](https://cloud.githubusercontent.com/assets/2168125/20784086/0521195c-b7d3-11e6-8537-bc33a593c025.png)

执行后  
![image](https://cloud.githubusercontent.com/assets/2168125/20784101/18b61f30-b7d3-11e6-8489-78f2c4cb9af8.png)

一直就一个连接啊

**Comment by zoujingli** [comment]
![image](https://cloud.githubusercontent.com/assets/4349951/20784180/abf3b8d4-b7d3-11e6-9d77-4d951483ae18.png)
![image](https://cloud.githubusercontent.com/assets/4349951/20784211/d4311cc4-b7d3-11e6-93bf-664f54e21751.png)
还在增加

**Comment by zoujingli** [comment]
不好意思，好像是业务部分代码添加的

**Comment by lindaoling** [comment]
兄弟，22年了，我这还有这个问题，你是怎么解决的

**Comment by zoujingli** [comment]
> 兄弟，22年了，我这还有这个问题，你是怎么解决的

数据查询时，不要使用 db 方法，注意不要使用 new Query 创建新连接等类似的方式
