### ISSUE TITLE
关于命令行执行 php think queue:work --daemon 报错

### ISSUE THREAD

**Issue by ChenJiaXu** [top-think/think-queue#54]
[InvalidArgumentException]
  There are no commands defined in the "queue" namespace.

**Comment by konohanaruto** [comment]
请问这个问题解决了吗？我也碰到了相同的问题，在5.0，这个命令好像不存在。

**Comment by hqb421** [comment]
我也是这个问题，一点办法也没有，本地win测试正常，一到线上就失灵时不灵，不灵的时候就报这个错误

**Comment by 916724955** [comment]
我遇到执行这个命令报错
![image](https://user-images.githubusercontent.com/22145934/118630803-73ab0d00-b801-11eb-81c4-562ed2e4d2a1.png)
这个是什么原因？

**Comment by konohanaruto** [comment]
我已经转行了，兄弟，你这命令我也看不懂啊。

**Comment by 916724955** [comment]
解决了，是redis扩展问题，不匹配
