### ISSUE TITLE
现在运行后，会在runtime/log下记录很多日志

### ISSUE THREAD

**Issue by SifuLi** [top-think/think-queue#6]
php think queue:work --daemon
会在runtime/log下记录很多日志，之前在调试模式下也没有的，是哪里的问题呢，不想要这么多。日志里全是这个，其它日志都不好找

[ 2016-12-09T11:37:45+08:00 ] 0.0.0.0 0.0.0.0 CLI 
[ log ] cmd:think queue:work --queue=default --delay=0 --memory=128 --sleep=3 --tries=0 [运行时间：3.074919s][吞吐率：0.33req/s] [内存消耗：1,807.00kb] [文件加载：72]
[ info ] [ DB ] INIT mysql
[ info ] [ LOG ] INIT file
[ sql ] [ SQL ] SHOW COLUMNS FROM `jobs_queue` [ RunTime:0.001548s ]
[ sql ] [ SQL ] UPDATE `jobs_queue`  SET `reserved`=0,`reserved_at`=NULL,`attempts`=attempts + 1  WHERE  `queue` = 'default'  AND `reserved` = 1  AND `reserved_at` <= 1481254602 [ RunTime:0.000654s ]
[ sql ] [ SQL ] SELECT * FROM `jobs_queue` WHERE  `queue` = 'default'  AND `reserved` = 0  AND `available_at` <= 1481254662 ORDER BY `id`  asc LIMIT 1   FOR UPDATE [ RunTime:0.000779s ]

---------------------------------------------------------------

**Comment by yunwuxin** [comment]
关闭调试模式   

之前也有的  因为之前框架的日志不是实时写的  一直放在内存里   停止的时候 一起写进日志文件的  这样会导致内存爆掉  

现在命令模式下 100条日志 就会写一次
