### ISSUE TITLE
今后会支持 Beanstalk 和 RabbitMQ 吗?

### ISSUE THREAD

**Issue by jayazhao** [top-think/think-queue#60]
请问今后会支持 Beanstalk 和 RabbitMQ 吗?

**Comment by no-serve-people** [comment]
同问 laravel可以配置beanstalk

**Comment by yunwuxin** [comment]
驱动 都是可以自己扩展的  内置的只是几个常用的

**Comment by sonhineboy** [comment]
这个扩展时基于官方的加上了rabbitmq,并优化了部分代码，欢迎star
https://github.com/sonhineboy/tp-queue
