### ISSUE TITLE
$job->delete();无法删除任务,think-queue一直会重试任务，直到失败

### ISSUE THREAD

**Issue by YLJIOS** [top-think/think-queue#62]
**thinkPHP5.0.20**
**think-queue 1.1.5**
think-queue驱动为 database

**问题是任务一直在重试直到失败，没法停止**

![qq 20180810102937](https://user-images.githubusercontent.com/13409767/43935941-d9a9c1ce-9c88-11e8-9c07-1616de71da50.png)
![qq 20180810103006](https://user-images.githubusercontent.com/13409767/43935943-da05f05c-9c88-11e8-9f2d-64cba43256ab.png)

**Comment by dafa168** [comment]
@yunwuxin  他也眼睛不好。

**Comment by yunwuxin** [comment]
@dafa168 你眼睛是真的不好
他这个问题跟你的可不一样
人家这个写的是对的
