### ISSUE TITLE
win下，redis不能执行队列的问题

### ISSUE THREAD

**Issue by fkcoward** [top-think/think-queue#63]
thinkphp5，window下，later模式，队列里添加一条可以执行，但是只要是添加一条以上，就不能执行。
我自己将connector下的Redis.php里的pushExpiredJobsOntoNewQueue修改如下：
`protected function pushExpiredJobsOntoNewQueue($to, $jobs, $attempt = true)
    {
        if ($attempt) {
            foreach ($jobs as &$job) {
                $attempts = json_decode($job, true)['attempts'];
                $job      = $this->setMeta($job, 'attempts', $attempts + 1);
            }
        }
        if(isset($job)){
            unset($job);
        }
        foreach ($jobs as $job){
            call_user_func_array([$this->redis, 'rPush'], [$to, $job]);
        }
    }`
这样就可以了，请问是什么原因

**Comment by orchie** [comment]
我也遇到这个问题了，linux服务器上没问题，本地windows不执行，命令行有输出，但没有实际执行。

**Comment by fkcoward** [comment]
> 我也遇到这个问题了，linux服务器上没问题，本地windows不执行，命令行有输出，但没有实际执行。
我记得win执行的时候，是redis删除了，但是没有添加进待执行的表里，所以我按照自己的想法改了那条语句，然后就没问题了，不知道怎么回事
