### ISSUE TITLE
队列支持不够丰富，希望支持rabbitmq kafka

### ISSUE THREAD

**Issue by yuxianhua** [top-think/think-queue#75]
rabbitmq和kafka在企业中用的较多，建议增加rabbitmq和kafka的扩展

**Comment by yunwuxin** [comment]
自定义驱动扩展

**Comment by sonhineboy** [comment]
这个扩展时基于官方的加上了rabbitmq,并优化了部分代码，欢迎star
https://github.com/sonhineboy/tp-queue
