### ISSUE TITLE
在任务A中发布任务B，任务B不会执行

### ISSUE THREAD

**Issue by xzusoft** [top-think/think-queue#78]
在任务A中发布任务B，任务B不会执行
class A{
    
    public function fire(Job $job, $data){
            $jobClass = 'app\\home\\queue\\B';//
           $data = ['name' => 'myname'];//附加数据
           $queueName = 'addData';//队列名称
           Queue::push($jobClass, $data, $queueName);
            $job->delete();
          
    }

}
class B{
    
    public function fire(Job $job, $data){
            //B 中任务
            $job->delete();
          
    }

}

**Comment by cattong** [comment]
是在控制台命令下吗

**Comment by xzusoft** [comment]
是的

**Comment by cattong** [comment]
> 是的

在控制台下的，队列确实有些问题。我实测的Queue::later也不行，但网页上的可以。

**Comment by yunwuxin** [comment]
哪个版本

**Comment by yunwuxin** [comment]
什么系统

**Comment by cattong** [comment]
> 什么系统

centos +php7.0 +redis  代码可以看 https://github.com/youyiio/beyongx/blob/master/application/common/model/ArticleModel.php

**Comment by cattong** [comment]
> 什么系统

crontab 定时，执行 php think xxx 这个命令后，内部有调用执行消息队列，Queue::push的消息是有执行，但Queue::later的消息没有执行。实测过。 "topthink/think-queue": "^2.0"

**Comment by yunwuxin** [comment]
刚刚测试过 没有问题  可以看下你们redis里的数据
