### ISSUE TITLE
framework6.0 think-queue3.0.0，队列redis驱动，添加到redis但是不会执行任务

### ISSUE THREAD

**Issue by lhnbsp** [top-think/think-queue#79]
framework6.0 think-queue3.0.0，队列redis驱动，执行php think queue:listen命令后，查看任务添加到redis列表里，但是未执行任务相关操作，查看日志报错：[2019-04-30T14:31:54+08:00][ error ] [0]Argument 2 passed to think\queue\Worker::process() must be an instance of think\queue\Job, null given, called in E:\Xampp\WWW\tp\vendor\topthink\think-queue\src\queue\Worker.php on line 261[E:\Xampp\WWW\tp\vendor\topthink\think-queue\src\queue\Worker.php:296]

一直找不到原因，所以又下载了tp5.1框架，think-queue2.0.4，还是redis驱动，队列成功执行

**Comment by lwying** [comment]
改成同步执行模式流程畅通，使用redis驱动push正常，调用work命令，无法执行

**Comment by lhnbsp** [comment]
> 改成同步执行模式流程畅通，使用redis驱动push正常，调用work命令，无法执行

我们俩问题应该一样??我也是同步模式流程完全正常，异步push成功，redis库里面也可以看到push的任务数据，但是任务不执行，查看runtime日志文件，报错，应该是任务执行过程中的报错
