### ISSUE TITLE
listen模式，work进程超时后，为什么listen也结束掉

### ISSUE THREAD

**Issue by 327100395** [top-think/think-queue#84]
listen模式，work进程超时后，为什么listen也结束掉，listen结束后其他的任务怎么办？
比如导出一个excel表，数据太多的话，导出超时了，listen也结束掉了，哪其他的导出excel表任务数据少的怎么办?
感觉应该这样，work超时了，listen结束掉这个work,给个回调，然后listen继续创建work进程

**Comment by yunwuxin** [comment]
listen并不会结束

**Comment by 327100395** [comment]
结束了

**Comment by Airam1016** [comment]
我也会，超时就被摁了

**Comment by Airam1016** [comment]
![image](https://user-images.githubusercontent.com/28509575/170241426-fe0925e7-3ca8-4db4-b77d-4d379ac230e6.png)
