### ISSUE TITLE
Redis 长链接在创建时是否应当加上 persistent_id 参数

### ISSUE THREAD

**Issue by DongDavid** [top-think/think-queue#87]
当我的queue使用redis驱动时，且选择了长链接模式。
此时thinkphp-queue建立redis长链接时，没有在pconnect方法中加入persistent_id参数。
此时这个连接的db默认使用0.
然后我的应用有另一个模块也使用了长链接。且使用的是db 1.
当我的queue在运行的过程中。另一个应用使用了这个长链接，并且select 1 改了db。
这个时候，queue也会变的使用了db 1 。 此时db0 中的数据不就用不了了？

是不是queue自己使用自己独有的一个长链接会好一点？
![image](https://user-images.githubusercontent.com/18623095/61112914-8e065800-a4bf-11e9-8ff5-f4594f1e6870.png)
![image](https://user-images.githubusercontent.com/18623095/61112999-baba6f80-a4bf-11e9-99c1-b6d1fe87bd0e.png)

**Comment by DongDavid** [comment]
```php
public function redisTest()
{
    // queue 建立了长链接
    $redis = new \Redis();
    $redis->pconnect('lnmp-redis');
    // queue 使用了db 0
    $redis->select(0);
    // queue 插入了任务
    $redis->set('aa','bb');
    dump($redis->get('aa'));
    // 其他应用使用了这个长链接
    $redis2 = new \Redis();
    $redis2->pconnect('lnmp-redis');
    // 其他应用把db 改成了1
    $redis2->select(1);
    
    // queue 取不到插入的任务了
    dump($redis->get('aa'));
    
    // 其他应用又好心的切回来了
    $redis->select(0);
    // queue能取到任务了
    dump($redis->get('aa'));
}
```

**Comment by 2-3-8-4-0-3-6-9-9-2** [comment]
redis默认有16个数据库，有人喜欢把不同的数据 存到不同的数据库里，这时候persistent_id参数就非常关键了。只有 pconnect 长连接才有设置persistent_id参数的必要.
一般切换数据库是用 $redis->select(3)，但是因为redis 内部是有 线程池的，下一次操作别的数据库还要重新切换回来: $redis->select(0)，这样可能会导致数据错乱：本来想存到3号数据库的东西却存到了10号数据库。
我感觉比较好的做法是， 使用单例模式，不同的数据库使用不同的对象，在构造函数里pconnect连接redis时，传入 persistent_id 参数 "db_10" ，$redis10->pconnect('127.0.0.1', 6379, 3, 'db_10'); ，并选择好想要操作的数据库$redis->select(3)，这样数据就不会乱。

$redis8 = RedisAliMulti::getRedisInstance(8);
$redis9 = RedisAliMulti::getRedisInstance(9);
$redis8->getConnect()->set('我将保存在8号数据库', '888888888', 600);
$redis9->getConnect()->set('我将保存在9号数据库', '999999999', 600);

**Comment by yunwuxin** [comment]
这种情况 直接用connect就可以了   现在支持断线重连了
