### ISSUE TITLE
5.2.*-dev composer 3.0安装不了，报错如下

### ISSUE THREAD

**Issue by lhnbsp** [top-think/think-queue#88]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for topthink/think-queue ^3.0 -> satisfiable by topthink/think-queue[v3.0.0, v3.0.1, v3.0.2].
    - Can only install one of: topthink/framework[6.0.x-dev, 5.2.x-dev].
    - Can only install one of: topthink/framework[6.0.x-dev, 5.2.x-dev].
    - Can only install one of: topthink/framework[6.0.x-dev, 5.2.x-dev].
    - Conclusion: install topthink/framework 6.0.x-dev
    - Installation request for topthink/framework 5.2.*-dev -> satisfiable by topthink/framework[5.2.x-dev].

Installation failed, reverting ./composer.json to its original content.

**Comment by ghost** [comment]
3.0 是给tp6用的

**Comment by DanRan-hcy** [comment]
composer require topthink/think-queue 2.0.4
用这个版本

**Comment by DanRan-hcy** [comment]
composer require topthink/think-queue 2.0.4
我5.1用的这个版本
