### ISSUE TITLE
执行区别

### ISSUE THREAD

**Issue by Alex-Yuen** [top-think/think-queue#9]
php think queue:listen

php think queue:work --daemon（不加--daemon为执行单个任务）

两个是一起执行,还是分开的两种不同执行方式,有啥区别

为什么用listen 执行cpu占用会很高

能否开多个work ,...............里面的任务会不会重复执行

**Comment by lqqllt** [comment]
我也追加一个问题，我cmd执行php think queue:listen 和 php think queue:work --daemon 感觉没反应，没啥效果，具体是怎么一个实现过程，能举个栗子，给个完整的流程案例？

**Comment by coolseven** [comment]
@Alex-Yuen 
### listen 模式
执行 `php thin queue:listen` 命令后，listen 命令所在的进程会使用 `proc_open('php think queue:work')` 来打开一个新的 work 进程,  listen 进程 和 work 进程可以通过 proc_open 创建的管道来通信。 
这种模式下，listen 进程负责管理 work 进程， work 进程则负责处理单个任务后退出。
work 进程退出后， listen 进程会再次创建一个新的 work 进程，来处理下一个任务。
work 进程超时后，listen 进程会及时结束 work 进程。

### work + daemon 模式
执行 `php thin queue:work --daemon` 命令后， work 进程内部会开启一个 while 循环， 如果存在需要消费的消息，则取出一条消息，然后进行消费，消费完成之后，循环会继续。 这种模式下，一直只有一个work 进程。

### 区别
1. listen 模式下，每个 work 进程被创建之后，work 进程中运行的代码基本上都是最新的，
 而在 work + daemon 模式下，代码如果有更改，则需要手动重启 work 进程
2. listen 模式下，work 进程如果发生超时（比如死循环...） ，可以依靠 listen 进程来结束自己，
而在 work + daemon 模式下，如果某个循环中出现了死循环，那么 work 进程可能就永远出不来了... (当然，也有一些方式去解决这个问题)
3. listen 模式由于每次处理完一个消息，就会重新创建一个新的 work 进程，因此在消息很多的情况下，性能要弱于 work + daemon 模式。
4. 不知道 think-queue 的 work 模式以后会不会增加对 SIGALARM 等信号的支持，如果会的话，那么后期work + daemon 应该可以取代 listen 模式

**Comment by leogorden** [comment]
> 我也追加一个问题，我cmd执行php think queue:listen 和 php think queue:work --daemon 感觉没反应，没啥效果，具体是怎么一个实现过程，能举个栗子，给个完整的流程案例？

我也有同样的疑问，不清楚这个消息队列的扩展应该用在什么地方

**Comment by 849159061** [comment]
> > 我也追加了一个问题，我cmd执行php think queue:listen 和php think queue:work --daemon 感觉没有反应，没啥效果，具体是怎么一个实现过程，能举个栗子，给个完整的流程案例？
> 
> 我也有同样的疑问，知识分子这个消息的扩展性应该在地方用

我也有疑问，也就一直看到process推送队列，但却不消费
